spring.application.name=apiAndroidBackend
spring.datasource.url=jdbc:mariadb://localhost:3305/adopcion_animales
spring.datasource.username=root
spring.datasource.password=1n3s4lm4nd0.1
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
server.address=0.0.0.0
server.port=8080

# Cloudinary
cloudinary.cloud-name=dxrkgjhge
cloudinary.api-key=138266452257119
cloudinary.api-secret=VmjukDYWI39Q5yCRSBoOGxcmGMI
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB